version: "3.8"
services:
  jupyter-notebook:
    container_name: jupyter-notebook
    build: ./jupyter-notebook
    ports:
      - "8888:8888"
      - "6006:6006"
  app-web:
    container_name: web-app
    build: ./web-app
    ports:
      - "5000:5000"
